/*
 * AI Horde
 *
 * The API documentation for the AI Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.StableHorde.Api.Model;
using Knedlex.StableHorde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.StableHorde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing ActiveModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ActiveModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ActiveModel
        //private ActiveModel instance;

        public ActiveModelTests()
        {
            // TODO uncomment below to create an instance of ActiveModel
            //instance = new ActiveModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ActiveModel
        /// </summary>
        [Fact]
        public void ActiveModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" ActiveModel
            //Assert.IsType<ActiveModel>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }

        /// <summary>
        /// Test the property 'Performance'
        /// </summary>
        [Fact]
        public void PerformanceTest()
        {
            // TODO unit test for the property 'Performance'
        }

        /// <summary>
        /// Test the property 'Queued'
        /// </summary>
        [Fact]
        public void QueuedTest()
        {
            // TODO unit test for the property 'Queued'
        }

        /// <summary>
        /// Test the property 'Jobs'
        /// </summary>
        [Fact]
        public void JobsTest()
        {
            // TODO unit test for the property 'Jobs'
        }

        /// <summary>
        /// Test the property 'Eta'
        /// </summary>
        [Fact]
        public void EtaTest()
        {
            // TODO unit test for the property 'Eta'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
    }
}
