/*
 * AI Horde
 *
 * The API documentation for the AI Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.StableHorde.Api.Model;
using Knedlex.StableHorde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.StableHorde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing AddWorkerTimeout
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddWorkerTimeoutTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddWorkerTimeout
        //private AddWorkerTimeout instance;

        public AddWorkerTimeoutTests()
        {
            // TODO uncomment below to create an instance of AddWorkerTimeout
            //instance = new AddWorkerTimeout();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddWorkerTimeout
        /// </summary>
        [Fact]
        public void AddWorkerTimeoutInstanceTest()
        {
            // TODO uncomment below to test "IsType" AddWorkerTimeout
            //Assert.IsType<AddWorkerTimeout>(instance);
        }

        /// <summary>
        /// Test the property 'Days'
        /// </summary>
        [Fact]
        public void DaysTest()
        {
            // TODO unit test for the property 'Days'
        }
    }
}
