/*
 * AI Horde
 *
 * The API documentation for the AI Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.StableHorde.Api.Model;
using Knedlex.StableHorde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.StableHorde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing GenerationPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GenerationPayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GenerationPayload
        //private GenerationPayload instance;

        public GenerationPayloadTests()
        {
            // TODO uncomment below to create an instance of GenerationPayload
            //instance = new GenerationPayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GenerationPayload
        /// </summary>
        [Fact]
        public void GenerationPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" GenerationPayload
            //Assert.IsType<GenerationPayload>(instance);
        }

        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Fact]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Skipped'
        /// </summary>
        [Fact]
        public void SkippedTest()
        {
            // TODO unit test for the property 'Skipped'
        }
    }
}
