/*
 * AI Horde
 *
 * The API documentation for the AI Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.StableHorde.Api.Model;
using Knedlex.StableHorde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.StableHorde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing HordePerformance
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HordePerformanceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HordePerformance
        //private HordePerformance instance;

        public HordePerformanceTests()
        {
            // TODO uncomment below to create an instance of HordePerformance
            //instance = new HordePerformance();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HordePerformance
        /// </summary>
        [Fact]
        public void HordePerformanceInstanceTest()
        {
            // TODO uncomment below to test "IsType" HordePerformance
            //Assert.IsType<HordePerformance>(instance);
        }

        /// <summary>
        /// Test the property 'QueuedRequests'
        /// </summary>
        [Fact]
        public void QueuedRequestsTest()
        {
            // TODO unit test for the property 'QueuedRequests'
        }

        /// <summary>
        /// Test the property 'QueuedTextRequests'
        /// </summary>
        [Fact]
        public void QueuedTextRequestsTest()
        {
            // TODO unit test for the property 'QueuedTextRequests'
        }

        /// <summary>
        /// Test the property 'WorkerCount'
        /// </summary>
        [Fact]
        public void WorkerCountTest()
        {
            // TODO unit test for the property 'WorkerCount'
        }

        /// <summary>
        /// Test the property 'TextWorkerCount'
        /// </summary>
        [Fact]
        public void TextWorkerCountTest()
        {
            // TODO unit test for the property 'TextWorkerCount'
        }

        /// <summary>
        /// Test the property 'ThreadCount'
        /// </summary>
        [Fact]
        public void ThreadCountTest()
        {
            // TODO unit test for the property 'ThreadCount'
        }

        /// <summary>
        /// Test the property 'TextThreadCount'
        /// </summary>
        [Fact]
        public void TextThreadCountTest()
        {
            // TODO unit test for the property 'TextThreadCount'
        }

        /// <summary>
        /// Test the property 'QueuedMegapixelsteps'
        /// </summary>
        [Fact]
        public void QueuedMegapixelstepsTest()
        {
            // TODO unit test for the property 'QueuedMegapixelsteps'
        }

        /// <summary>
        /// Test the property 'PastMinuteMegapixelsteps'
        /// </summary>
        [Fact]
        public void PastMinuteMegapixelstepsTest()
        {
            // TODO unit test for the property 'PastMinuteMegapixelsteps'
        }

        /// <summary>
        /// Test the property 'QueuedForms'
        /// </summary>
        [Fact]
        public void QueuedFormsTest()
        {
            // TODO unit test for the property 'QueuedForms'
        }

        /// <summary>
        /// Test the property 'InterrogatorCount'
        /// </summary>
        [Fact]
        public void InterrogatorCountTest()
        {
            // TODO unit test for the property 'InterrogatorCount'
        }

        /// <summary>
        /// Test the property 'InterrogatorThreadCount'
        /// </summary>
        [Fact]
        public void InterrogatorThreadCountTest()
        {
            // TODO unit test for the property 'InterrogatorThreadCount'
        }

        /// <summary>
        /// Test the property 'QueuedTokens'
        /// </summary>
        [Fact]
        public void QueuedTokensTest()
        {
            // TODO unit test for the property 'QueuedTokens'
        }

        /// <summary>
        /// Test the property 'PastMinuteTokens'
        /// </summary>
        [Fact]
        public void PastMinuteTokensTest()
        {
            // TODO unit test for the property 'PastMinuteTokens'
        }
    }
}
