/*
 * AI Horde
 *
 * The API documentation for the AI Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.StableHorde.Api.Model;
using Knedlex.StableHorde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.StableHorde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing PopInputKobold
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PopInputKoboldTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PopInputKobold
        //private PopInputKobold instance;

        public PopInputKoboldTests()
        {
            // TODO uncomment below to create an instance of PopInputKobold
            //instance = new PopInputKobold();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PopInputKobold
        /// </summary>
        [Fact]
        public void PopInputKoboldInstanceTest()
        {
            // TODO uncomment below to test "IsType" PopInputKobold
            //Assert.IsType<PopInputKobold>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'PriorityUsernames'
        /// </summary>
        [Fact]
        public void PriorityUsernamesTest()
        {
            // TODO unit test for the property 'PriorityUsernames'
        }

        /// <summary>
        /// Test the property 'Nsfw'
        /// </summary>
        [Fact]
        public void NsfwTest()
        {
            // TODO unit test for the property 'Nsfw'
        }

        /// <summary>
        /// Test the property 'Models'
        /// </summary>
        [Fact]
        public void ModelsTest()
        {
            // TODO unit test for the property 'Models'
        }

        /// <summary>
        /// Test the property 'BridgeAgent'
        /// </summary>
        [Fact]
        public void BridgeAgentTest()
        {
            // TODO unit test for the property 'BridgeAgent'
        }

        /// <summary>
        /// Test the property 'Threads'
        /// </summary>
        [Fact]
        public void ThreadsTest()
        {
            // TODO unit test for the property 'Threads'
        }

        /// <summary>
        /// Test the property 'RequireUpfrontKudos'
        /// </summary>
        [Fact]
        public void RequireUpfrontKudosTest()
        {
            // TODO unit test for the property 'RequireUpfrontKudos'
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'MaxLength'
        /// </summary>
        [Fact]
        public void MaxLengthTest()
        {
            // TODO unit test for the property 'MaxLength'
        }

        /// <summary>
        /// Test the property 'MaxContextLength'
        /// </summary>
        [Fact]
        public void MaxContextLengthTest()
        {
            // TODO unit test for the property 'MaxContextLength'
        }

        /// <summary>
        /// Test the property 'Softprompts'
        /// </summary>
        [Fact]
        public void SoftpromptsTest()
        {
            // TODO unit test for the property 'Softprompts'
        }
    }
}
