/*
 * AI Horde
 *
 * The API documentation for the AI Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.StableHorde.Api.Model;
using Knedlex.StableHorde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.StableHorde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing PostAwardKudosRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostAwardKudosRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostAwardKudosRequest
        //private PostAwardKudosRequest instance;

        public PostAwardKudosRequestTests()
        {
            // TODO uncomment below to create an instance of PostAwardKudosRequest
            //instance = new PostAwardKudosRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostAwardKudosRequest
        /// </summary>
        [Fact]
        public void PostAwardKudosRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PostAwardKudosRequest
            //Assert.IsType<PostAwardKudosRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
    }
}
