/*
 * AI Horde
 *
 * The API documentation for the AI Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.StableHorde.Api.Model;
using Knedlex.StableHorde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.StableHorde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing PutHordeModesRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PutHordeModesRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PutHordeModesRequest
        //private PutHordeModesRequest instance;

        public PutHordeModesRequestTests()
        {
            // TODO uncomment below to create an instance of PutHordeModesRequest
            //instance = new PutHordeModesRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PutHordeModesRequest
        /// </summary>
        [Fact]
        public void PutHordeModesRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PutHordeModesRequest
            //Assert.IsType<PutHordeModesRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Maintenance'
        /// </summary>
        [Fact]
        public void MaintenanceTest()
        {
            // TODO unit test for the property 'Maintenance'
        }

        /// <summary>
        /// Test the property 'InviteOnly'
        /// </summary>
        [Fact]
        public void InviteOnlyTest()
        {
            // TODO unit test for the property 'InviteOnly'
        }

        /// <summary>
        /// Test the property 'Raid'
        /// </summary>
        [Fact]
        public void RaidTest()
        {
            // TODO unit test for the property 'Raid'
        }
    }
}
