/*
 * AI Horde
 *
 * The API documentation for the AI Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.StableHorde.Api.Model;
using Knedlex.StableHorde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.StableHorde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing SharedKeyDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SharedKeyDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SharedKeyDetails
        //private SharedKeyDetails instance;

        public SharedKeyDetailsTests()
        {
            // TODO uncomment below to create an instance of SharedKeyDetails
            //instance = new SharedKeyDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SharedKeyDetails
        /// </summary>
        [Fact]
        public void SharedKeyDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" SharedKeyDetails
            //Assert.IsType<SharedKeyDetails>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Kudos'
        /// </summary>
        [Fact]
        public void KudosTest()
        {
            // TODO unit test for the property 'Kudos'
        }

        /// <summary>
        /// Test the property 'Expiry'
        /// </summary>
        [Fact]
        public void ExpiryTest()
        {
            // TODO unit test for the property 'Expiry'
        }

        /// <summary>
        /// Test the property 'Utilized'
        /// </summary>
        [Fact]
        public void UtilizedTest()
        {
            // TODO unit test for the property 'Utilized'
        }

        /// <summary>
        /// Test the property 'MaxImagePixels'
        /// </summary>
        [Fact]
        public void MaxImagePixelsTest()
        {
            // TODO unit test for the property 'MaxImagePixels'
        }

        /// <summary>
        /// Test the property 'MaxImageSteps'
        /// </summary>
        [Fact]
        public void MaxImageStepsTest()
        {
            // TODO unit test for the property 'MaxImageSteps'
        }

        /// <summary>
        /// Test the property 'MaxTextTokens'
        /// </summary>
        [Fact]
        public void MaxTextTokensTest()
        {
            // TODO unit test for the property 'MaxTextTokens'
        }
    }
}
