/*
 * AI Horde
 *
 * The API documentation for the AI Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.StableHorde.Api.Model;
using Knedlex.StableHorde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.StableHorde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing StatsTxtTotals
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StatsTxtTotalsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StatsTxtTotals
        //private StatsTxtTotals instance;

        public StatsTxtTotalsTests()
        {
            // TODO uncomment below to create an instance of StatsTxtTotals
            //instance = new StatsTxtTotals();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StatsTxtTotals
        /// </summary>
        [Fact]
        public void StatsTxtTotalsInstanceTest()
        {
            // TODO uncomment below to test "IsType" StatsTxtTotals
            //Assert.IsType<StatsTxtTotals>(instance);
        }

        /// <summary>
        /// Test the property 'Minute'
        /// </summary>
        [Fact]
        public void MinuteTest()
        {
            // TODO unit test for the property 'Minute'
        }

        /// <summary>
        /// Test the property 'Hour'
        /// </summary>
        [Fact]
        public void HourTest()
        {
            // TODO unit test for the property 'Hour'
        }

        /// <summary>
        /// Test the property 'Day'
        /// </summary>
        [Fact]
        public void DayTest()
        {
            // TODO unit test for the property 'Day'
        }

        /// <summary>
        /// Test the property 'Month'
        /// </summary>
        [Fact]
        public void MonthTest()
        {
            // TODO unit test for the property 'Month'
        }

        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
    }
}
