/*
 * AI Horde
 *
 * The API documentation for the AI Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.StableHorde.Api.Model;
using Knedlex.StableHorde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.StableHorde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing UserThingRecords
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserThingRecordsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserThingRecords
        //private UserThingRecords instance;

        public UserThingRecordsTests()
        {
            // TODO uncomment below to create an instance of UserThingRecords
            //instance = new UserThingRecords();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserThingRecords
        /// </summary>
        [Fact]
        public void UserThingRecordsInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserThingRecords
            //Assert.IsType<UserThingRecords>(instance);
        }

        /// <summary>
        /// Test the property 'Megapixelsteps'
        /// </summary>
        [Fact]
        public void MegapixelstepsTest()
        {
            // TODO unit test for the property 'Megapixelsteps'
        }

        /// <summary>
        /// Test the property 'Tokens'
        /// </summary>
        [Fact]
        public void TokensTest()
        {
            // TODO unit test for the property 'Tokens'
        }
    }
}
