/*
 * AI Horde
 *
 * The API documentation for the AI Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.StableHorde.Api.Model;
using Knedlex.StableHorde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.StableHorde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing WorkerDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WorkerDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WorkerDetails
        //private WorkerDetails instance;

        public WorkerDetailsTests()
        {
            // TODO uncomment below to create an instance of WorkerDetails
            //instance = new WorkerDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WorkerDetails
        /// </summary>
        [Fact]
        public void WorkerDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" WorkerDetails
            //Assert.IsType<WorkerDetails>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Online'
        /// </summary>
        [Fact]
        public void OnlineTest()
        {
            // TODO unit test for the property 'Online'
        }

        /// <summary>
        /// Test the property 'RequestsFulfilled'
        /// </summary>
        [Fact]
        public void RequestsFulfilledTest()
        {
            // TODO unit test for the property 'RequestsFulfilled'
        }

        /// <summary>
        /// Test the property 'KudosRewards'
        /// </summary>
        [Fact]
        public void KudosRewardsTest()
        {
            // TODO unit test for the property 'KudosRewards'
        }

        /// <summary>
        /// Test the property 'KudosDetails'
        /// </summary>
        [Fact]
        public void KudosDetailsTest()
        {
            // TODO unit test for the property 'KudosDetails'
        }

        /// <summary>
        /// Test the property 'Performance'
        /// </summary>
        [Fact]
        public void PerformanceTest()
        {
            // TODO unit test for the property 'Performance'
        }

        /// <summary>
        /// Test the property 'Threads'
        /// </summary>
        [Fact]
        public void ThreadsTest()
        {
            // TODO unit test for the property 'Threads'
        }

        /// <summary>
        /// Test the property 'Uptime'
        /// </summary>
        [Fact]
        public void UptimeTest()
        {
            // TODO unit test for the property 'Uptime'
        }

        /// <summary>
        /// Test the property 'MaintenanceMode'
        /// </summary>
        [Fact]
        public void MaintenanceModeTest()
        {
            // TODO unit test for the property 'MaintenanceMode'
        }

        /// <summary>
        /// Test the property 'Paused'
        /// </summary>
        [Fact]
        public void PausedTest()
        {
            // TODO unit test for the property 'Paused'
        }

        /// <summary>
        /// Test the property 'Info'
        /// </summary>
        [Fact]
        public void InfoTest()
        {
            // TODO unit test for the property 'Info'
        }

        /// <summary>
        /// Test the property 'Nsfw'
        /// </summary>
        [Fact]
        public void NsfwTest()
        {
            // TODO unit test for the property 'Nsfw'
        }

        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Fact]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }

        /// <summary>
        /// Test the property 'Ipaddr'
        /// </summary>
        [Fact]
        public void IpaddrTest()
        {
            // TODO unit test for the property 'Ipaddr'
        }

        /// <summary>
        /// Test the property 'Trusted'
        /// </summary>
        [Fact]
        public void TrustedTest()
        {
            // TODO unit test for the property 'Trusted'
        }

        /// <summary>
        /// Test the property 'Flagged'
        /// </summary>
        [Fact]
        public void FlaggedTest()
        {
            // TODO unit test for the property 'Flagged'
        }

        /// <summary>
        /// Test the property 'Suspicious'
        /// </summary>
        [Fact]
        public void SuspiciousTest()
        {
            // TODO unit test for the property 'Suspicious'
        }

        /// <summary>
        /// Test the property 'UncompletedJobs'
        /// </summary>
        [Fact]
        public void UncompletedJobsTest()
        {
            // TODO unit test for the property 'UncompletedJobs'
        }

        /// <summary>
        /// Test the property 'Models'
        /// </summary>
        [Fact]
        public void ModelsTest()
        {
            // TODO unit test for the property 'Models'
        }

        /// <summary>
        /// Test the property 'Forms'
        /// </summary>
        [Fact]
        public void FormsTest()
        {
            // TODO unit test for the property 'Forms'
        }

        /// <summary>
        /// Test the property 'Team'
        /// </summary>
        [Fact]
        public void TeamTest()
        {
            // TODO unit test for the property 'Team'
        }

        /// <summary>
        /// Test the property 'Contact'
        /// </summary>
        [Fact]
        public void ContactTest()
        {
            // TODO unit test for the property 'Contact'
        }

        /// <summary>
        /// Test the property 'BridgeAgent'
        /// </summary>
        [Fact]
        public void BridgeAgentTest()
        {
            // TODO unit test for the property 'BridgeAgent'
        }

        /// <summary>
        /// Test the property 'MaxPixels'
        /// </summary>
        [Fact]
        public void MaxPixelsTest()
        {
            // TODO unit test for the property 'MaxPixels'
        }

        /// <summary>
        /// Test the property 'MegapixelstepsGenerated'
        /// </summary>
        [Fact]
        public void MegapixelstepsGeneratedTest()
        {
            // TODO unit test for the property 'MegapixelstepsGenerated'
        }

        /// <summary>
        /// Test the property 'Img2img'
        /// </summary>
        [Fact]
        public void Img2imgTest()
        {
            // TODO unit test for the property 'Img2img'
        }

        /// <summary>
        /// Test the property 'Painting'
        /// </summary>
        [Fact]
        public void PaintingTest()
        {
            // TODO unit test for the property 'Painting'
        }

        /// <summary>
        /// Test the property 'PostProcessing'
        /// </summary>
        [Fact]
        public void PostProcessingTest()
        {
            // TODO unit test for the property 'PostProcessing'
        }

        /// <summary>
        /// Test the property 'Lora'
        /// </summary>
        [Fact]
        public void LoraTest()
        {
            // TODO unit test for the property 'Lora'
        }

        /// <summary>
        /// Test the property 'MaxLength'
        /// </summary>
        [Fact]
        public void MaxLengthTest()
        {
            // TODO unit test for the property 'MaxLength'
        }

        /// <summary>
        /// Test the property 'MaxContextLength'
        /// </summary>
        [Fact]
        public void MaxContextLengthTest()
        {
            // TODO unit test for the property 'MaxContextLength'
        }

        /// <summary>
        /// Test the property 'TokensGenerated'
        /// </summary>
        [Fact]
        public void TokensGeneratedTest()
        {
            // TODO unit test for the property 'TokensGenerated'
        }
    }
}
