/*
 * AI Horde
 *
 * The API documentation for the AI Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Knedlex.StableHorde.Api.Client.OpenAPIDateConverter;

namespace Knedlex.StableHorde.Api.Model
{
    /// <summary>
    /// AddTimeoutIPInput
    /// </summary>
    [DataContract(Name = "AddTimeoutIPInput")]
    public partial class AddTimeoutIPInput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddTimeoutIPInput" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AddTimeoutIPInput() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AddTimeoutIPInput" /> class.
        /// </summary>
        /// <param name="ipaddr">The IP address or CIDR to add from timeout. (required).</param>
        /// <param name="hours">For how many hours to put this IP in timeout. (required).</param>
        public AddTimeoutIPInput(string ipaddr = default(string), int hours = default(int))
        {
            // to ensure "ipaddr" is required (not null)
            if (ipaddr == null)
            {
                throw new ArgumentNullException("ipaddr is a required property for AddTimeoutIPInput and cannot be null");
            }
            this.Ipaddr = ipaddr;
            this.Hours = hours;
        }

        /// <summary>
        /// The IP address or CIDR to add from timeout.
        /// </summary>
        /// <value>The IP address or CIDR to add from timeout.</value>
        /// <example>127.0.0.1</example>
        [DataMember(Name = "ipaddr", IsRequired = true, EmitDefaultValue = true)]
        public string Ipaddr { get; set; }

        /// <summary>
        /// For how many hours to put this IP in timeout.
        /// </summary>
        /// <value>For how many hours to put this IP in timeout.</value>
        /// <example>24</example>
        [DataMember(Name = "hours", IsRequired = true, EmitDefaultValue = true)]
        public int Hours { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AddTimeoutIPInput {\n");
            sb.Append("  Ipaddr: ").Append(Ipaddr).Append("\n");
            sb.Append("  Hours: ").Append(Hours).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Ipaddr (string) maxLength
            if (this.Ipaddr != null && this.Ipaddr.Length > 40)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Ipaddr, length must be less than 40.", new [] { "Ipaddr" });
            }

            // Ipaddr (string) minLength
            if (this.Ipaddr != null && this.Ipaddr.Length < 7)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Ipaddr, length must be greater than 7.", new [] { "Ipaddr" });
            }

            // Hours (int) maximum
            if (this.Hours > (int)720)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Hours, must be a value less than or equal to 720.", new [] { "Hours" });
            }

            // Hours (int) minimum
            if (this.Hours < (int)1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Hours, must be a value greater than or equal to 1.", new [] { "Hours" });
            }

            yield break;
        }
    }

}
