/*
 * AI Horde
 *
 * The API documentation for the AI Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Knedlex.StableHorde.Api.Client.OpenAPIDateConverter;

namespace Knedlex.StableHorde.Api.Model
{
    /// <summary>
    /// UserRecords
    /// </summary>
    [DataContract(Name = "UserRecords")]
    public partial class UserRecords : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserRecords" /> class.
        /// </summary>
        /// <param name="usage">usage.</param>
        /// <param name="contribution">contribution.</param>
        /// <param name="fulfillment">fulfillment.</param>
        /// <param name="request">request.</param>
        public UserRecords(UserThingRecords usage = default(UserThingRecords), UserThingRecords contribution = default(UserThingRecords), UserAmountRecords fulfillment = default(UserAmountRecords), UserAmountRecords request = default(UserAmountRecords))
        {
            this.Usage = usage;
            this.Contribution = contribution;
            this.Fulfillment = fulfillment;
            this.Request = request;
        }

        /// <summary>
        /// Gets or Sets Usage
        /// </summary>
        [DataMember(Name = "usage", EmitDefaultValue = false)]
        public UserThingRecords Usage { get; set; }

        /// <summary>
        /// Gets or Sets Contribution
        /// </summary>
        [DataMember(Name = "contribution", EmitDefaultValue = false)]
        public UserThingRecords Contribution { get; set; }

        /// <summary>
        /// Gets or Sets Fulfillment
        /// </summary>
        [DataMember(Name = "fulfillment", EmitDefaultValue = false)]
        public UserAmountRecords Fulfillment { get; set; }

        /// <summary>
        /// Gets or Sets Request
        /// </summary>
        [DataMember(Name = "request", EmitDefaultValue = false)]
        public UserAmountRecords Request { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserRecords {\n");
            sb.Append("  Usage: ").Append(Usage).Append("\n");
            sb.Append("  Contribution: ").Append(Contribution).Append("\n");
            sb.Append("  Fulfillment: ").Append(Fulfillment).Append("\n");
            sb.Append("  Request: ").Append(Request).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
