/*
 * AI Horde
 *
 * The API documentation for the AI Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StableHorde.Api.Api;
using StableHorde.Api.Model;
using StableHorde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StableHorde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing AestheticRating
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AestheticRatingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AestheticRating
        //private AestheticRating instance;

        public AestheticRatingTests()
        {
            // TODO uncomment below to create an instance of AestheticRating
            //instance = new AestheticRating();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AestheticRating
        /// </summary>
        [Fact]
        public void AestheticRatingInstanceTest()
        {
            // TODO uncomment below to test "IsType" AestheticRating
            //Assert.IsType<AestheticRating>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Rating'
        /// </summary>
        [Fact]
        public void RatingTest()
        {
            // TODO unit test for the property 'Rating'
        }
        /// <summary>
        /// Test the property 'Artifacts'
        /// </summary>
        [Fact]
        public void ArtifactsTest()
        {
            // TODO unit test for the property 'Artifacts'
        }

    }

}
