/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StableHorde.Api.Api;
using StableHorde.Api.Model;
using StableHorde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StableHorde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing ContributionsDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContributionsDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ContributionsDetails
        //private ContributionsDetails instance;

        public ContributionsDetailsTests()
        {
            // TODO uncomment below to create an instance of ContributionsDetails
            //instance = new ContributionsDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ContributionsDetails
        /// </summary>
        [Fact]
        public void ContributionsDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ContributionsDetails
            //Assert.IsType<ContributionsDetails>(instance);
        }


        /// <summary>
        /// Test the property 'Fulfillments'
        /// </summary>
        [Fact]
        public void FulfillmentsTest()
        {
            // TODO unit test for the property 'Fulfillments'
        }

    }

}
