/*
 * AI Horde
 *
 * The API documentation for the AI Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StableHorde.Api.Api;
using StableHorde.Api.Model;
using StableHorde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StableHorde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing FilterRegex
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FilterRegexTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FilterRegex
        //private FilterRegex instance;

        public FilterRegexTests()
        {
            // TODO uncomment below to create an instance of FilterRegex
            //instance = new FilterRegex();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FilterRegex
        /// </summary>
        [Fact]
        public void FilterRegexInstanceTest()
        {
            // TODO uncomment below to test "IsType" FilterRegex
            //Assert.IsType<FilterRegex>(instance);
        }


        /// <summary>
        /// Test the property 'FilterType'
        /// </summary>
        [Fact]
        public void FilterTypeTest()
        {
            // TODO unit test for the property 'FilterType'
        }
        /// <summary>
        /// Test the property 'Regex'
        /// </summary>
        [Fact]
        public void RegexTest()
        {
            // TODO unit test for the property 'Regex'
        }

    }

}
