/*
 * AI Horde
 *
 * The API documentation for the AI Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StableHorde.Api.Api;
using StableHorde.Api.Model;
using StableHorde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StableHorde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing GenerationInputStable
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GenerationInputStableTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GenerationInputStable
        //private GenerationInputStable instance;

        public GenerationInputStableTests()
        {
            // TODO uncomment below to create an instance of GenerationInputStable
            //instance = new GenerationInputStable();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GenerationInputStable
        /// </summary>
        [Fact]
        public void GenerationInputStableInstanceTest()
        {
            // TODO uncomment below to test "IsType" GenerationInputStable
            //Assert.IsType<GenerationInputStable>(instance);
        }


        /// <summary>
        /// Test the property 'Prompt'
        /// </summary>
        [Fact]
        public void PromptTest()
        {
            // TODO unit test for the property 'Prompt'
        }
        /// <summary>
        /// Test the property 'Params'
        /// </summary>
        [Fact]
        public void ParamsTest()
        {
            // TODO unit test for the property 'Params'
        }
        /// <summary>
        /// Test the property 'Nsfw'
        /// </summary>
        [Fact]
        public void NsfwTest()
        {
            // TODO unit test for the property 'Nsfw'
        }
        /// <summary>
        /// Test the property 'TrustedWorkers'
        /// </summary>
        [Fact]
        public void TrustedWorkersTest()
        {
            // TODO unit test for the property 'TrustedWorkers'
        }
        /// <summary>
        /// Test the property 'SlowWorkers'
        /// </summary>
        [Fact]
        public void SlowWorkersTest()
        {
            // TODO unit test for the property 'SlowWorkers'
        }
        /// <summary>
        /// Test the property 'CensorNsfw'
        /// </summary>
        [Fact]
        public void CensorNsfwTest()
        {
            // TODO unit test for the property 'CensorNsfw'
        }
        /// <summary>
        /// Test the property 'Workers'
        /// </summary>
        [Fact]
        public void WorkersTest()
        {
            // TODO unit test for the property 'Workers'
        }
        /// <summary>
        /// Test the property 'WorkerBlacklist'
        /// </summary>
        [Fact]
        public void WorkerBlacklistTest()
        {
            // TODO unit test for the property 'WorkerBlacklist'
        }
        /// <summary>
        /// Test the property 'Models'
        /// </summary>
        [Fact]
        public void ModelsTest()
        {
            // TODO unit test for the property 'Models'
        }
        /// <summary>
        /// Test the property 'SourceImage'
        /// </summary>
        [Fact]
        public void SourceImageTest()
        {
            // TODO unit test for the property 'SourceImage'
        }
        /// <summary>
        /// Test the property 'SourceProcessing'
        /// </summary>
        [Fact]
        public void SourceProcessingTest()
        {
            // TODO unit test for the property 'SourceProcessing'
        }
        /// <summary>
        /// Test the property 'SourceMask'
        /// </summary>
        [Fact]
        public void SourceMaskTest()
        {
            // TODO unit test for the property 'SourceMask'
        }
        /// <summary>
        /// Test the property 'R2'
        /// </summary>
        [Fact]
        public void R2Test()
        {
            // TODO unit test for the property 'R2'
        }
        /// <summary>
        /// Test the property 'Shared'
        /// </summary>
        [Fact]
        public void SharedTest()
        {
            // TODO unit test for the property 'Shared'
        }
        /// <summary>
        /// Test the property 'ReplacementFilter'
        /// </summary>
        [Fact]
        public void ReplacementFilterTest()
        {
            // TODO unit test for the property 'ReplacementFilter'
        }
        /// <summary>
        /// Test the property 'DryRun'
        /// </summary>
        [Fact]
        public void DryRunTest()
        {
            // TODO unit test for the property 'DryRun'
        }
        /// <summary>
        /// Test the property 'ProxiedAccount'
        /// </summary>
        [Fact]
        public void ProxiedAccountTest()
        {
            // TODO unit test for the property 'ProxiedAccount'
        }
        /// <summary>
        /// Test the property 'DisableBatching'
        /// </summary>
        [Fact]
        public void DisableBatchingTest()
        {
            // TODO unit test for the property 'DisableBatching'
        }
        /// <summary>
        /// Test the property 'Webhook'
        /// </summary>
        [Fact]
        public void WebhookTest()
        {
            // TODO unit test for the property 'Webhook'
        }

    }

}
