/*
 * AI Horde
 *
 * The API documentation for the AI Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StableHorde.Api.Api;
using StableHorde.Api.Model;
using StableHorde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StableHorde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing GenerationMetadataStable
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GenerationMetadataStableTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GenerationMetadataStable
        //private GenerationMetadataStable instance;

        public GenerationMetadataStableTests()
        {
            // TODO uncomment below to create an instance of GenerationMetadataStable
            //instance = new GenerationMetadataStable();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GenerationMetadataStable
        /// </summary>
        [Fact]
        public void GenerationMetadataStableInstanceTest()
        {
            // TODO uncomment below to test "IsType" GenerationMetadataStable
            //Assert.IsType<GenerationMetadataStable>(instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'Ref'
        /// </summary>
        [Fact]
        public void RefTest()
        {
            // TODO unit test for the property 'Ref'
        }

    }

}
