/*
 * AI Horde
 *
 * The API documentation for the AI Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StableHorde.Api.Api;
using StableHorde.Api.Model;
using StableHorde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StableHorde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing GenerationPayloadStable
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GenerationPayloadStableTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GenerationPayloadStable
        //private GenerationPayloadStable instance;

        public GenerationPayloadStableTests()
        {
            // TODO uncomment below to create an instance of GenerationPayloadStable
            //instance = new GenerationPayloadStable();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GenerationPayloadStable
        /// </summary>
        [Fact]
        public void GenerationPayloadStableInstanceTest()
        {
            // TODO uncomment below to test "IsType" GenerationPayloadStable
            //Assert.IsType<GenerationPayloadStable>(instance);
        }


        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Fact]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Ids'
        /// </summary>
        [Fact]
        public void IdsTest()
        {
            // TODO unit test for the property 'Ids'
        }
        /// <summary>
        /// Test the property 'Skipped'
        /// </summary>
        [Fact]
        public void SkippedTest()
        {
            // TODO unit test for the property 'Skipped'
        }
        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Fact]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }
        /// <summary>
        /// Test the property 'SourceImage'
        /// </summary>
        [Fact]
        public void SourceImageTest()
        {
            // TODO unit test for the property 'SourceImage'
        }
        /// <summary>
        /// Test the property 'SourceProcessing'
        /// </summary>
        [Fact]
        public void SourceProcessingTest()
        {
            // TODO unit test for the property 'SourceProcessing'
        }
        /// <summary>
        /// Test the property 'SourceMask'
        /// </summary>
        [Fact]
        public void SourceMaskTest()
        {
            // TODO unit test for the property 'SourceMask'
        }
        /// <summary>
        /// Test the property 'R2Upload'
        /// </summary>
        [Fact]
        public void R2UploadTest()
        {
            // TODO unit test for the property 'R2Upload'
        }
        /// <summary>
        /// Test the property 'R2Uploads'
        /// </summary>
        [Fact]
        public void R2UploadsTest()
        {
            // TODO unit test for the property 'R2Uploads'
        }

    }

}
