/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StableHorde.Api.Api;
using StableHorde.Api.Model;
using StableHorde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StableHorde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing ModelGenerationInputStableAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModelGenerationInputStableAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ModelGenerationInputStableAllOf
        //private ModelGenerationInputStableAllOf instance;

        public ModelGenerationInputStableAllOfTests()
        {
            // TODO uncomment below to create an instance of ModelGenerationInputStableAllOf
            //instance = new ModelGenerationInputStableAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ModelGenerationInputStableAllOf
        /// </summary>
        [Fact]
        public void ModelGenerationInputStableAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" ModelGenerationInputStableAllOf
            //Assert.IsType<ModelGenerationInputStableAllOf>(instance);
        }


        /// <summary>
        /// Test the property 'Steps'
        /// </summary>
        [Fact]
        public void StepsTest()
        {
            // TODO unit test for the property 'Steps'
        }
        /// <summary>
        /// Test the property 'N'
        /// </summary>
        [Fact]
        public void NTest()
        {
            // TODO unit test for the property 'N'
        }

    }

}
