/*
 * AI Horde
 *
 * The API documentation for the AI Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StableHorde.Api.Api;
using StableHorde.Api.Model;
using StableHorde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StableHorde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing ModelInterrogationFormPayloadStable
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModelInterrogationFormPayloadStableTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ModelInterrogationFormPayloadStable
        //private ModelInterrogationFormPayloadStable instance;

        public ModelInterrogationFormPayloadStableTests()
        {
            // TODO uncomment below to create an instance of ModelInterrogationFormPayloadStable
            //instance = new ModelInterrogationFormPayloadStable();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ModelInterrogationFormPayloadStable
        /// </summary>
        [Fact]
        public void ModelInterrogationFormPayloadStableInstanceTest()
        {
            // TODO uncomment below to test "IsType" ModelInterrogationFormPayloadStable
            //Assert.IsType<ModelInterrogationFormPayloadStable>(instance);
        }


        /// <summary>
        /// Test the property ''
        /// </summary>
        [Fact]
        public void Test()
        {
            // TODO unit test for the property ''
        }

    }

}
