/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StableHorde.Api.Api;
using StableHorde.Api.Model;
using StableHorde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StableHorde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing ModelPayloadStable
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModelPayloadStableTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ModelPayloadStable
        //private ModelPayloadStable instance;

        public ModelPayloadStableTests()
        {
            // TODO uncomment below to create an instance of ModelPayloadStable
            //instance = new ModelPayloadStable();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ModelPayloadStable
        /// </summary>
        [Fact]
        public void ModelPayloadStableInstanceTest()
        {
            // TODO uncomment below to test "IsType" ModelPayloadStable
            //Assert.IsType<ModelPayloadStable>(instance);
        }


        /// <summary>
        /// Test the property 'SamplerName'
        /// </summary>
        [Fact]
        public void SamplerNameTest()
        {
            // TODO unit test for the property 'SamplerName'
        }
        /// <summary>
        /// Test the property 'Toggles'
        /// </summary>
        [Fact]
        public void TogglesTest()
        {
            // TODO unit test for the property 'Toggles'
        }
        /// <summary>
        /// Test the property 'CfgScale'
        /// </summary>
        [Fact]
        public void CfgScaleTest()
        {
            // TODO unit test for the property 'CfgScale'
        }
        /// <summary>
        /// Test the property 'DenoisingStrength'
        /// </summary>
        [Fact]
        public void DenoisingStrengthTest()
        {
            // TODO unit test for the property 'DenoisingStrength'
        }
        /// <summary>
        /// Test the property 'Seed'
        /// </summary>
        [Fact]
        public void SeedTest()
        {
            // TODO unit test for the property 'Seed'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Fact]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Fact]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }
        /// <summary>
        /// Test the property 'SeedVariation'
        /// </summary>
        [Fact]
        public void SeedVariationTest()
        {
            // TODO unit test for the property 'SeedVariation'
        }
        /// <summary>
        /// Test the property 'UseGfpgan'
        /// </summary>
        [Fact]
        public void UseGfpganTest()
        {
            // TODO unit test for the property 'UseGfpgan'
        }
        /// <summary>
        /// Test the property 'UseRealEsrgan'
        /// </summary>
        [Fact]
        public void UseRealEsrganTest()
        {
            // TODO unit test for the property 'UseRealEsrgan'
        }
        /// <summary>
        /// Test the property 'UseLdsr'
        /// </summary>
        [Fact]
        public void UseLdsrTest()
        {
            // TODO unit test for the property 'UseLdsr'
        }
        /// <summary>
        /// Test the property 'UseUpscaling'
        /// </summary>
        [Fact]
        public void UseUpscalingTest()
        {
            // TODO unit test for the property 'UseUpscaling'
        }
        /// <summary>
        /// Test the property 'Prompt'
        /// </summary>
        [Fact]
        public void PromptTest()
        {
            // TODO unit test for the property 'Prompt'
        }
        /// <summary>
        /// Test the property 'DdimSteps'
        /// </summary>
        [Fact]
        public void DdimStepsTest()
        {
            // TODO unit test for the property 'DdimSteps'
        }
        /// <summary>
        /// Test the property 'NIter'
        /// </summary>
        [Fact]
        public void NIterTest()
        {
            // TODO unit test for the property 'NIter'
        }
        /// <summary>
        /// Test the property 'UseNsfwCensor'
        /// </summary>
        [Fact]
        public void UseNsfwCensorTest()
        {
            // TODO unit test for the property 'UseNsfwCensor'
        }

    }

}
