/*
 * AI Horde
 *
 * The API documentation for the AI Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StableHorde.Api.Api;
using StableHorde.Api.Model;
using StableHorde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StableHorde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing ModifyWorkerInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModifyWorkerInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ModifyWorkerInput
        //private ModifyWorkerInput instance;

        public ModifyWorkerInputTests()
        {
            // TODO uncomment below to create an instance of ModifyWorkerInput
            //instance = new ModifyWorkerInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ModifyWorkerInput
        /// </summary>
        [Fact]
        public void ModifyWorkerInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" ModifyWorkerInput
            //Assert.IsType<ModifyWorkerInput>(instance);
        }


        /// <summary>
        /// Test the property 'Maintenance'
        /// </summary>
        [Fact]
        public void MaintenanceTest()
        {
            // TODO unit test for the property 'Maintenance'
        }
        /// <summary>
        /// Test the property 'MaintenanceMsg'
        /// </summary>
        [Fact]
        public void MaintenanceMsgTest()
        {
            // TODO unit test for the property 'MaintenanceMsg'
        }
        /// <summary>
        /// Test the property 'Paused'
        /// </summary>
        [Fact]
        public void PausedTest()
        {
            // TODO unit test for the property 'Paused'
        }
        /// <summary>
        /// Test the property 'Info'
        /// </summary>
        [Fact]
        public void InfoTest()
        {
            // TODO unit test for the property 'Info'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Team'
        /// </summary>
        [Fact]
        public void TeamTest()
        {
            // TODO unit test for the property 'Team'
        }

    }

}
