/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StableHorde.Api.Api;
using StableHorde.Api.Model;
using StableHorde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StableHorde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing Newspiece
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NewspieceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Newspiece
        //private Newspiece instance;

        public NewspieceTests()
        {
            // TODO uncomment below to create an instance of Newspiece
            //instance = new Newspiece();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Newspiece
        /// </summary>
        [Fact]
        public void NewspieceInstanceTest()
        {
            // TODO uncomment below to test "IsType" Newspiece
            //Assert.IsType<Newspiece>(instance);
        }


        /// <summary>
        /// Test the property 'DatePublished'
        /// </summary>
        [Fact]
        public void DatePublishedTest()
        {
            // TODO unit test for the property 'DatePublished'
        }
        /// <summary>
        /// Test the property '_Newspiece'
        /// </summary>
        [Fact]
        public void _NewspieceTest()
        {
            // TODO unit test for the property '_Newspiece'
        }
        /// <summary>
        /// Test the property 'Importance'
        /// </summary>
        [Fact]
        public void ImportanceTest()
        {
            // TODO unit test for the property 'Importance'
        }

    }

}
