/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StableHorde.Api.Api;
using StableHorde.Api.Model;
using StableHorde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StableHorde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing PopInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PopInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PopInput
        //private PopInput instance;

        public PopInputTests()
        {
            // TODO uncomment below to create an instance of PopInput
            //instance = new PopInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PopInput
        /// </summary>
        [Fact]
        public void PopInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" PopInput
            //Assert.IsType<PopInput>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'PriorityUsernames'
        /// </summary>
        [Fact]
        public void PriorityUsernamesTest()
        {
            // TODO unit test for the property 'PriorityUsernames'
        }
        /// <summary>
        /// Test the property 'Nsfw'
        /// </summary>
        [Fact]
        public void NsfwTest()
        {
            // TODO unit test for the property 'Nsfw'
        }
        /// <summary>
        /// Test the property 'Blacklist'
        /// </summary>
        [Fact]
        public void BlacklistTest()
        {
            // TODO unit test for the property 'Blacklist'
        }
        /// <summary>
        /// Test the property 'Models'
        /// </summary>
        [Fact]
        public void ModelsTest()
        {
            // TODO unit test for the property 'Models'
        }
        /// <summary>
        /// Test the property 'BridgeVersion'
        /// </summary>
        [Fact]
        public void BridgeVersionTest()
        {
            // TODO unit test for the property 'BridgeVersion'
        }

    }

}
