/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StableHorde.Api.Api;
using StableHorde.Api.Model;
using StableHorde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StableHorde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing PopInputStable
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PopInputStableTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PopInputStable
        //private PopInputStable instance;

        public PopInputStableTests()
        {
            // TODO uncomment below to create an instance of PopInputStable
            //instance = new PopInputStable();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PopInputStable
        /// </summary>
        [Fact]
        public void PopInputStableInstanceTest()
        {
            // TODO uncomment below to test "IsType" PopInputStable
            //Assert.IsType<PopInputStable>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'PriorityUsernames'
        /// </summary>
        [Fact]
        public void PriorityUsernamesTest()
        {
            // TODO unit test for the property 'PriorityUsernames'
        }
        /// <summary>
        /// Test the property 'Nsfw'
        /// </summary>
        [Fact]
        public void NsfwTest()
        {
            // TODO unit test for the property 'Nsfw'
        }
        /// <summary>
        /// Test the property 'Blacklist'
        /// </summary>
        [Fact]
        public void BlacklistTest()
        {
            // TODO unit test for the property 'Blacklist'
        }
        /// <summary>
        /// Test the property 'Models'
        /// </summary>
        [Fact]
        public void ModelsTest()
        {
            // TODO unit test for the property 'Models'
        }
        /// <summary>
        /// Test the property 'BridgeVersion'
        /// </summary>
        [Fact]
        public void BridgeVersionTest()
        {
            // TODO unit test for the property 'BridgeVersion'
        }
        /// <summary>
        /// Test the property 'MaxPixels'
        /// </summary>
        [Fact]
        public void MaxPixelsTest()
        {
            // TODO unit test for the property 'MaxPixels'
        }
        /// <summary>
        /// Test the property 'AllowImg2img'
        /// </summary>
        [Fact]
        public void AllowImg2imgTest()
        {
            // TODO unit test for the property 'AllowImg2img'
        }
        /// <summary>
        /// Test the property 'AllowPainting'
        /// </summary>
        [Fact]
        public void AllowPaintingTest()
        {
            // TODO unit test for the property 'AllowPainting'
        }
        /// <summary>
        /// Test the property 'AllowUnsafeIpaddr'
        /// </summary>
        [Fact]
        public void AllowUnsafeIpaddrTest()
        {
            // TODO unit test for the property 'AllowUnsafeIpaddr'
        }

    }

}
