/*
 * AI Horde
 *
 * The API documentation for the AI Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StableHorde.Api.Api;
using StableHorde.Api.Model;
using StableHorde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StableHorde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing PostFiltersRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostFiltersRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostFiltersRequest
        //private PostFiltersRequest instance;

        public PostFiltersRequestTests()
        {
            // TODO uncomment below to create an instance of PostFiltersRequest
            //instance = new PostFiltersRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostFiltersRequest
        /// </summary>
        [Fact]
        public void PostFiltersRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PostFiltersRequest
            //Assert.IsType<PostFiltersRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Prompt'
        /// </summary>
        [Fact]
        public void PromptTest()
        {
            // TODO unit test for the property 'Prompt'
        }
        /// <summary>
        /// Test the property 'FilterType'
        /// </summary>
        [Fact]
        public void FilterTypeTest()
        {
            // TODO unit test for the property 'FilterType'
        }

    }

}
