/*
 * AI Horde
 *
 * The API documentation for the AI Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StableHorde.Api.Api;
using StableHorde.Api.Model;
using StableHorde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StableHorde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing SubmitInputKoboldAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SubmitInputKoboldAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SubmitInputKoboldAllOf
        //private SubmitInputKoboldAllOf instance;

        public SubmitInputKoboldAllOfTests()
        {
            // TODO uncomment below to create an instance of SubmitInputKoboldAllOf
            //instance = new SubmitInputKoboldAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubmitInputKoboldAllOf
        /// </summary>
        [Fact]
        public void SubmitInputKoboldAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" SubmitInputKoboldAllOf
            //Assert.IsType<SubmitInputKoboldAllOf>(instance);
        }


        /// <summary>
        /// Test the property 'GenMetadata'
        /// </summary>
        [Fact]
        public void GenMetadataTest()
        {
            // TODO unit test for the property 'GenMetadata'
        }

    }

}
