/*
 * AI Horde
 *
 * The API documentation for the AI Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StableHorde.Api.Api;
using StableHorde.Api.Model;
using StableHorde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StableHorde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing SubmitInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SubmitInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SubmitInput
        //private SubmitInput instance;

        public SubmitInputTests()
        {
            // TODO uncomment below to create an instance of SubmitInput
            //instance = new SubmitInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubmitInput
        /// </summary>
        [Fact]
        public void SubmitInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" SubmitInput
            //Assert.IsType<SubmitInput>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Generation'
        /// </summary>
        [Fact]
        public void GenerationTest()
        {
            // TODO unit test for the property 'Generation'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

    }

}
