/*
 * AI Horde
 *
 * The API documentation for the AI Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StableHorde.Api.Api;
using StableHorde.Api.Model;
using StableHorde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StableHorde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing TeamDetailsAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TeamDetailsAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TeamDetailsAllOf
        //private TeamDetailsAllOf instance;

        public TeamDetailsAllOfTests()
        {
            // TODO uncomment below to create an instance of TeamDetailsAllOf
            //instance = new TeamDetailsAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TeamDetailsAllOf
        /// </summary>
        [Fact]
        public void TeamDetailsAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" TeamDetailsAllOf
            //Assert.IsType<TeamDetailsAllOf>(instance);
        }


        /// <summary>
        /// Test the property 'Info'
        /// </summary>
        [Fact]
        public void InfoTest()
        {
            // TODO unit test for the property 'Info'
        }
        /// <summary>
        /// Test the property 'RequestsFulfilled'
        /// </summary>
        [Fact]
        public void RequestsFulfilledTest()
        {
            // TODO unit test for the property 'RequestsFulfilled'
        }
        /// <summary>
        /// Test the property 'Kudos'
        /// </summary>
        [Fact]
        public void KudosTest()
        {
            // TODO unit test for the property 'Kudos'
        }
        /// <summary>
        /// Test the property 'Uptime'
        /// </summary>
        [Fact]
        public void UptimeTest()
        {
            // TODO unit test for the property 'Uptime'
        }
        /// <summary>
        /// Test the property 'Creator'
        /// </summary>
        [Fact]
        public void CreatorTest()
        {
            // TODO unit test for the property 'Creator'
        }
        /// <summary>
        /// Test the property 'WorkerCount'
        /// </summary>
        [Fact]
        public void WorkerCountTest()
        {
            // TODO unit test for the property 'WorkerCount'
        }
        /// <summary>
        /// Test the property 'Workers'
        /// </summary>
        [Fact]
        public void WorkersTest()
        {
            // TODO unit test for the property 'Workers'
        }
        /// <summary>
        /// Test the property 'Models'
        /// </summary>
        [Fact]
        public void ModelsTest()
        {
            // TODO unit test for the property 'Models'
        }

    }

}
