/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StableHorde.Api.Api;
using StableHorde.Api.Model;
using StableHorde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StableHorde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing UsageDetailsStableAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UsageDetailsStableAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UsageDetailsStableAllOf
        //private UsageDetailsStableAllOf instance;

        public UsageDetailsStableAllOfTests()
        {
            // TODO uncomment below to create an instance of UsageDetailsStableAllOf
            //instance = new UsageDetailsStableAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UsageDetailsStableAllOf
        /// </summary>
        [Fact]
        public void UsageDetailsStableAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" UsageDetailsStableAllOf
            //Assert.IsType<UsageDetailsStableAllOf>(instance);
        }


        /// <summary>
        /// Test the property 'Megapixelsteps'
        /// </summary>
        [Fact]
        public void MegapixelstepsTest()
        {
            // TODO unit test for the property 'Megapixelsteps'
        }

    }

}
