/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StableHorde.Api.Api;
using StableHorde.Api.Model;
using StableHorde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StableHorde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing UserDetailsStableAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserDetailsStableAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserDetailsStableAllOf
        //private UserDetailsStableAllOf instance;

        public UserDetailsStableAllOfTests()
        {
            // TODO uncomment below to create an instance of UserDetailsStableAllOf
            //instance = new UserDetailsStableAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserDetailsStableAllOf
        /// </summary>
        [Fact]
        public void UserDetailsStableAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserDetailsStableAllOf
            //Assert.IsType<UserDetailsStableAllOf>(instance);
        }


        /// <summary>
        /// Test the property 'KudosDetails'
        /// </summary>
        [Fact]
        public void KudosDetailsTest()
        {
            // TODO unit test for the property 'KudosDetails'
        }
        /// <summary>
        /// Test the property 'Usage'
        /// </summary>
        [Fact]
        public void UsageTest()
        {
            // TODO unit test for the property 'Usage'
        }
        /// <summary>
        /// Test the property 'Contributions'
        /// </summary>
        [Fact]
        public void ContributionsTest()
        {
            // TODO unit test for the property 'Contributions'
        }

    }

}
