/*
 * AI Horde
 *
 * The API documentation for the AI Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StableHorde.Api.Client.OpenAPIDateConverter;

namespace StableHorde.Api.Model
{
    /// <summary>
    /// InterrogationPopInput
    /// </summary>
    [DataContract(Name = "InterrogationPopInput")]
    public partial class InterrogationPopInput : IEquatable<InterrogationPopInput>, IValidatableObject
    {
        /// <summary>
        /// The type of interrogation this worker can fulfil.
        /// </summary>
        /// <value>The type of interrogation this worker can fulfil.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum FormsEnum
        {
            /// <summary>
            /// Enum Caption for value: caption
            /// </summary>
            [EnumMember(Value = "caption")]
            Caption = 1,

            /// <summary>
            /// Enum Interrogation for value: interrogation
            /// </summary>
            [EnumMember(Value = "interrogation")]
            Interrogation = 2,

            /// <summary>
            /// Enum Nsfw for value: nsfw
            /// </summary>
            [EnumMember(Value = "nsfw")]
            Nsfw = 3,

            /// <summary>
            /// Enum GFPGAN for value: GFPGAN
            /// </summary>
            [EnumMember(Value = "GFPGAN")]
            GFPGAN = 4,

            /// <summary>
            /// Enum RealESRGANX4plus for value: RealESRGAN_x4plus
            /// </summary>
            [EnumMember(Value = "RealESRGAN_x4plus")]
            RealESRGANX4plus = 5,

            /// <summary>
            /// Enum RealESRGANX2plus for value: RealESRGAN_x2plus
            /// </summary>
            [EnumMember(Value = "RealESRGAN_x2plus")]
            RealESRGANX2plus = 6,

            /// <summary>
            /// Enum RealESRGANX4plusAnime6B for value: RealESRGAN_x4plus_anime_6B
            /// </summary>
            [EnumMember(Value = "RealESRGAN_x4plus_anime_6B")]
            RealESRGANX4plusAnime6B = 7,

            /// <summary>
            /// Enum NMKDSiax for value: NMKD_Siax
            /// </summary>
            [EnumMember(Value = "NMKD_Siax")]
            NMKDSiax = 8,

            /// <summary>
            /// Enum _4xAnimeSharp for value: 4x_AnimeSharp
            /// </summary>
            [EnumMember(Value = "4x_AnimeSharp")]
            _4xAnimeSharp = 9,

            /// <summary>
            /// Enum CodeFormers for value: CodeFormers
            /// </summary>
            [EnumMember(Value = "CodeFormers")]
            CodeFormers = 10,

            /// <summary>
            /// Enum StripBackground for value: strip_background
            /// </summary>
            [EnumMember(Value = "strip_background")]
            StripBackground = 11

        }



        /// <summary>
        /// Gets or Sets Forms
        /// </summary>
        [DataMember(Name = "forms", EmitDefaultValue = false)]
        public List<FormsEnum> Forms { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="InterrogationPopInput" /> class.
        /// </summary>
        /// <param name="name">The Name of the Worker..</param>
        /// <param name="priorityUsernames">priorityUsernames.</param>
        /// <param name="forms">forms.</param>
        /// <param name="amount">The amount of forms to pop at the same time..</param>
        /// <param name="bridgeAgent">The worker name, version and website. (default to &quot;unknown&quot;).</param>
        /// <param name="threads">How many threads this worker is running. This is used to accurately the current power available in the horde..</param>
        /// <param name="maxTiles">The maximum amount of 512x512 tiles this worker can post-process..</param>
        public InterrogationPopInput(string name = default(string), List<string> priorityUsernames = default(List<string>), List<FormsEnum> forms = default(List<FormsEnum>), int amount = default(int), string bridgeAgent = "unknown", int threads = default(int), int maxTiles = default(int))
        {
            this.Name = name;
            this.PriorityUsernames = priorityUsernames;
            this.Forms = forms;
            this.Amount = amount;
            // use default value if no "bridgeAgent" provided
            this.BridgeAgent = bridgeAgent ?? "unknown";
            this.Threads = threads;
            this.MaxTiles = maxTiles;
        }

        /// <summary>
        /// The Name of the Worker.
        /// </summary>
        /// <value>The Name of the Worker.</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets PriorityUsernames
        /// </summary>
        [DataMember(Name = "priority_usernames", EmitDefaultValue = false)]
        public List<string> PriorityUsernames { get; set; }

        /// <summary>
        /// The amount of forms to pop at the same time.
        /// </summary>
        /// <value>The amount of forms to pop at the same time.</value>
        [DataMember(Name = "amount", EmitDefaultValue = false)]
        public int Amount { get; set; }

        /// <summary>
        /// The worker name, version and website.
        /// </summary>
        /// <value>The worker name, version and website.</value>
        [DataMember(Name = "bridge_agent", EmitDefaultValue = false)]
        public string BridgeAgent { get; set; }

        /// <summary>
        /// How many threads this worker is running. This is used to accurately the current power available in the horde.
        /// </summary>
        /// <value>How many threads this worker is running. This is used to accurately the current power available in the horde.</value>
        [DataMember(Name = "threads", EmitDefaultValue = false)]
        public int Threads { get; set; }

        /// <summary>
        /// The maximum amount of 512x512 tiles this worker can post-process.
        /// </summary>
        /// <value>The maximum amount of 512x512 tiles this worker can post-process.</value>
        [DataMember(Name = "max_tiles", EmitDefaultValue = false)]
        public int MaxTiles { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InterrogationPopInput {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  PriorityUsernames: ").Append(PriorityUsernames).Append("\n");
            sb.Append("  Forms: ").Append(Forms).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  BridgeAgent: ").Append(BridgeAgent).Append("\n");
            sb.Append("  Threads: ").Append(Threads).Append("\n");
            sb.Append("  MaxTiles: ").Append(MaxTiles).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InterrogationPopInput);
        }

        /// <summary>
        /// Returns true if InterrogationPopInput instances are equal
        /// </summary>
        /// <param name="input">Instance of InterrogationPopInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InterrogationPopInput input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.PriorityUsernames == input.PriorityUsernames ||
                    this.PriorityUsernames != null &&
                    input.PriorityUsernames != null &&
                    this.PriorityUsernames.SequenceEqual(input.PriorityUsernames)
                ) && 
                (
                    this.Forms == input.Forms ||
                    this.Forms.SequenceEqual(input.Forms)
                ) && 
                (
                    this.Amount == input.Amount ||
                    this.Amount.Equals(input.Amount)
                ) && 
                (
                    this.BridgeAgent == input.BridgeAgent ||
                    (this.BridgeAgent != null &&
                    this.BridgeAgent.Equals(input.BridgeAgent))
                ) && 
                (
                    this.Threads == input.Threads ||
                    this.Threads.Equals(input.Threads)
                ) && 
                (
                    this.MaxTiles == input.MaxTiles ||
                    this.MaxTiles.Equals(input.MaxTiles)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.PriorityUsernames != null)
                {
                    hashCode = (hashCode * 59) + this.PriorityUsernames.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Forms.GetHashCode();
                hashCode = (hashCode * 59) + this.Amount.GetHashCode();
                if (this.BridgeAgent != null)
                {
                    hashCode = (hashCode * 59) + this.BridgeAgent.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Threads.GetHashCode();
                hashCode = (hashCode * 59) + this.MaxTiles.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            // BridgeAgent (string) maxLength
            if (this.BridgeAgent != null && this.BridgeAgent.Length > 1000)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for BridgeAgent, length must be less than 1000.", new [] { "BridgeAgent" });
            }

            // Threads (int) maximum
            if (this.Threads > (int)100)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Threads, must be a value less than or equal to 100.", new [] { "Threads" });
            }

            // Threads (int) minimum
            if (this.Threads < (int)1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Threads, must be a value greater than or equal to 1.", new [] { "Threads" });
            }

            // MaxTiles (int) maximum
            if (this.MaxTiles > (int)256)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MaxTiles, must be a value less than or equal to 256.", new [] { "MaxTiles" });
            }

            // MaxTiles (int) minimum
            if (this.MaxTiles < (int)1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MaxTiles, must be a value greater than or equal to 1.", new [] { "MaxTiles" });
            }

            yield break;
        }
    }

}
