/*
 * AI Horde
 *
 * The API documentation for the AI Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StableHorde.Api.Client.OpenAPIDateConverter;

namespace StableHorde.Api.Model
{
    /// <summary>
    /// Newspiece
    /// </summary>
    [DataContract(Name = "Newspiece")]
    public partial class Newspiece : IEquatable<Newspiece>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Newspiece" /> class.
        /// </summary>
        /// <param name="datePublished">The date this newspiece was published..</param>
        /// <param name="newspiece">The actual piece of news..</param>
        /// <param name="importance">How critical this piece of news is..</param>
        public Newspiece(string datePublished = default(string), string newspiece = default(string), string importance = default(string))
        {
            this.DatePublished = datePublished;
            this._Newspiece = newspiece;
            this.Importance = importance;
        }

        /// <summary>
        /// The date this newspiece was published.
        /// </summary>
        /// <value>The date this newspiece was published.</value>
        [DataMember(Name = "date_published", EmitDefaultValue = false)]
        public string DatePublished { get; set; }

        /// <summary>
        /// The actual piece of news.
        /// </summary>
        /// <value>The actual piece of news.</value>
        [DataMember(Name = "newspiece", EmitDefaultValue = false)]
        public string _Newspiece { get; set; }

        /// <summary>
        /// How critical this piece of news is.
        /// </summary>
        /// <value>How critical this piece of news is.</value>
        [DataMember(Name = "importance", EmitDefaultValue = false)]
        public string Importance { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Newspiece {\n");
            sb.Append("  DatePublished: ").Append(DatePublished).Append("\n");
            sb.Append("  _Newspiece: ").Append(_Newspiece).Append("\n");
            sb.Append("  Importance: ").Append(Importance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Newspiece);
        }

        /// <summary>
        /// Returns true if Newspiece instances are equal
        /// </summary>
        /// <param name="input">Instance of Newspiece to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Newspiece input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.DatePublished == input.DatePublished ||
                    (this.DatePublished != null &&
                    this.DatePublished.Equals(input.DatePublished))
                ) && 
                (
                    this._Newspiece == input._Newspiece ||
                    (this._Newspiece != null &&
                    this._Newspiece.Equals(input._Newspiece))
                ) && 
                (
                    this.Importance == input.Importance ||
                    (this.Importance != null &&
                    this.Importance.Equals(input.Importance))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DatePublished != null)
                {
                    hashCode = (hashCode * 59) + this.DatePublished.GetHashCode();
                }
                if (this._Newspiece != null)
                {
                    hashCode = (hashCode * 59) + this._Newspiece.GetHashCode();
                }
                if (this.Importance != null)
                {
                    hashCode = (hashCode * 59) + this.Importance.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
