/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StableHorde.Api.Client.OpenAPIDateConverter;

namespace StableHorde.Api.Model
{
    /// <summary>
    /// NoValidRequestFound
    /// </summary>
    [DataContract(Name = "NoValidRequestFound")]
    public partial class NoValidRequestFound : IEquatable<NoValidRequestFound>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NoValidRequestFound" /> class.
        /// </summary>
        /// <param name="workerId">How many waiting requests were skipped because they demanded a specific worker.</param>
        /// <param name="performance">How many waiting requests were skipped because they demanded a specific worker.</param>
        /// <param name="nsfw">How many waiting requests were skipped because they demanded a nsfw generation which this worker does not provide..</param>
        /// <param name="blacklist">How many waiting requests were skipped because they demanded a generation with a word that this worker does not accept..</param>
        /// <param name="untrusted">How many waiting requests were skipped because they demanded a trusted worker which this worker is not..</param>
        /// <param name="models">How many waiting requests were skipped because they demanded a different model than what this worker provides..</param>
        public NoValidRequestFound(int workerId = default(int), int performance = default(int), int nsfw = default(int), int blacklist = default(int), int untrusted = default(int), int models = default(int))
        {
            this.WorkerId = workerId;
            this.Performance = performance;
            this.Nsfw = nsfw;
            this.Blacklist = blacklist;
            this.Untrusted = untrusted;
            this.Models = models;
        }

        /// <summary>
        /// How many waiting requests were skipped because they demanded a specific worker
        /// </summary>
        /// <value>How many waiting requests were skipped because they demanded a specific worker</value>
        [DataMember(Name = "worker_id", EmitDefaultValue = false)]
        public int WorkerId { get; set; }

        /// <summary>
        /// How many waiting requests were skipped because they demanded a specific worker
        /// </summary>
        /// <value>How many waiting requests were skipped because they demanded a specific worker</value>
        [DataMember(Name = "performance", EmitDefaultValue = false)]
        public int Performance { get; set; }

        /// <summary>
        /// How many waiting requests were skipped because they demanded a nsfw generation which this worker does not provide.
        /// </summary>
        /// <value>How many waiting requests were skipped because they demanded a nsfw generation which this worker does not provide.</value>
        [DataMember(Name = "nsfw", EmitDefaultValue = false)]
        public int Nsfw { get; set; }

        /// <summary>
        /// How many waiting requests were skipped because they demanded a generation with a word that this worker does not accept.
        /// </summary>
        /// <value>How many waiting requests were skipped because they demanded a generation with a word that this worker does not accept.</value>
        [DataMember(Name = "blacklist", EmitDefaultValue = false)]
        public int Blacklist { get; set; }

        /// <summary>
        /// How many waiting requests were skipped because they demanded a trusted worker which this worker is not.
        /// </summary>
        /// <value>How many waiting requests were skipped because they demanded a trusted worker which this worker is not.</value>
        [DataMember(Name = "untrusted", EmitDefaultValue = false)]
        public int Untrusted { get; set; }

        /// <summary>
        /// How many waiting requests were skipped because they demanded a different model than what this worker provides.
        /// </summary>
        /// <value>How many waiting requests were skipped because they demanded a different model than what this worker provides.</value>
        [DataMember(Name = "models", EmitDefaultValue = false)]
        public int Models { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NoValidRequestFound {\n");
            sb.Append("  WorkerId: ").Append(WorkerId).Append("\n");
            sb.Append("  Performance: ").Append(Performance).Append("\n");
            sb.Append("  Nsfw: ").Append(Nsfw).Append("\n");
            sb.Append("  Blacklist: ").Append(Blacklist).Append("\n");
            sb.Append("  Untrusted: ").Append(Untrusted).Append("\n");
            sb.Append("  Models: ").Append(Models).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NoValidRequestFound);
        }

        /// <summary>
        /// Returns true if NoValidRequestFound instances are equal
        /// </summary>
        /// <param name="input">Instance of NoValidRequestFound to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NoValidRequestFound input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.WorkerId == input.WorkerId ||
                    this.WorkerId.Equals(input.WorkerId)
                ) && 
                (
                    this.Performance == input.Performance ||
                    this.Performance.Equals(input.Performance)
                ) && 
                (
                    this.Nsfw == input.Nsfw ||
                    this.Nsfw.Equals(input.Nsfw)
                ) && 
                (
                    this.Blacklist == input.Blacklist ||
                    this.Blacklist.Equals(input.Blacklist)
                ) && 
                (
                    this.Untrusted == input.Untrusted ||
                    this.Untrusted.Equals(input.Untrusted)
                ) && 
                (
                    this.Models == input.Models ||
                    this.Models.Equals(input.Models)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.WorkerId.GetHashCode();
                hashCode = (hashCode * 59) + this.Performance.GetHashCode();
                hashCode = (hashCode * 59) + this.Nsfw.GetHashCode();
                hashCode = (hashCode * 59) + this.Blacklist.GetHashCode();
                hashCode = (hashCode * 59) + this.Untrusted.GetHashCode();
                hashCode = (hashCode * 59) + this.Models.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
