/*
 * AI Horde
 *
 * The API documentation for the AI Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StableHorde.Api.Client.OpenAPIDateConverter;

namespace StableHorde.Api.Model
{
    /// <summary>
    /// SubmitInputStableAllOf
    /// </summary>
    [DataContract(Name = "SubmitInputStable_allOf")]
    public partial class SubmitInputStableAllOf : IEquatable<SubmitInputStableAllOf>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SubmitInputStableAllOf" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SubmitInputStableAllOf() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SubmitInputStableAllOf" /> class.
        /// </summary>
        /// <param name="seed">The seed for this generation. (required).</param>
        /// <param name="censored">OBSOLETE (start using meta): If True, this resulting image has been censored. (default to false).</param>
        /// <param name="genMetadata">genMetadata.</param>
        public SubmitInputStableAllOf(int seed = default(int), bool censored = false, List<GenerationMetadataStable> genMetadata = default(List<GenerationMetadataStable>))
        {
            this.Seed = seed;
            this.Censored = censored;
            this.GenMetadata = genMetadata;
        }

        /// <summary>
        /// The seed for this generation.
        /// </summary>
        /// <value>The seed for this generation.</value>
        [DataMember(Name = "seed", IsRequired = true, EmitDefaultValue = true)]
        public int Seed { get; set; }

        /// <summary>
        /// OBSOLETE (start using meta): If True, this resulting image has been censored.
        /// </summary>
        /// <value>OBSOLETE (start using meta): If True, this resulting image has been censored.</value>
        [DataMember(Name = "censored", EmitDefaultValue = true)]
        public bool Censored { get; set; }

        /// <summary>
        /// Gets or Sets GenMetadata
        /// </summary>
        [DataMember(Name = "gen_metadata", EmitDefaultValue = false)]
        public List<GenerationMetadataStable> GenMetadata { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SubmitInputStableAllOf {\n");
            sb.Append("  Seed: ").Append(Seed).Append("\n");
            sb.Append("  Censored: ").Append(Censored).Append("\n");
            sb.Append("  GenMetadata: ").Append(GenMetadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SubmitInputStableAllOf);
        }

        /// <summary>
        /// Returns true if SubmitInputStableAllOf instances are equal
        /// </summary>
        /// <param name="input">Instance of SubmitInputStableAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SubmitInputStableAllOf input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Seed == input.Seed ||
                    this.Seed.Equals(input.Seed)
                ) && 
                (
                    this.Censored == input.Censored ||
                    this.Censored.Equals(input.Censored)
                ) && 
                (
                    this.GenMetadata == input.GenMetadata ||
                    this.GenMetadata != null &&
                    input.GenMetadata != null &&
                    this.GenMetadata.SequenceEqual(input.GenMetadata)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Seed.GetHashCode();
                hashCode = (hashCode * 59) + this.Censored.GetHashCode();
                if (this.GenMetadata != null)
                {
                    hashCode = (hashCode * 59) + this.GenMetadata.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
