/*
 * AI Horde
 *
 * The API documentation for the AI Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StableHorde.Api.Client.OpenAPIDateConverter;

namespace StableHorde.Api.Model
{
    /// <summary>
    /// SubmitInputKoboldAllOf
    /// </summary>
    [DataContract(Name = "SubmitInputKobold_allOf")]
    public partial class SubmitInputKoboldAllOf : IEquatable<SubmitInputKoboldAllOf>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SubmitInputKoboldAllOf" /> class.
        /// </summary>
        /// <param name="genMetadata">genMetadata.</param>
        public SubmitInputKoboldAllOf(List<GenerationMetadataKobold> genMetadata = default(List<GenerationMetadataKobold>))
        {
            this.GenMetadata = genMetadata;
        }

        /// <summary>
        /// Gets or Sets GenMetadata
        /// </summary>
        [DataMember(Name = "gen_metadata", EmitDefaultValue = false)]
        public List<GenerationMetadataKobold> GenMetadata { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SubmitInputKoboldAllOf {\n");
            sb.Append("  GenMetadata: ").Append(GenMetadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SubmitInputKoboldAllOf);
        }

        /// <summary>
        /// Returns true if SubmitInputKoboldAllOf instances are equal
        /// </summary>
        /// <param name="input">Instance of SubmitInputKoboldAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SubmitInputKoboldAllOf input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.GenMetadata == input.GenMetadata ||
                    this.GenMetadata != null &&
                    input.GenMetadata != null &&
                    this.GenMetadata.SequenceEqual(input.GenMetadata)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.GenMetadata != null)
                {
                    hashCode = (hashCode * 59) + this.GenMetadata.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
