/*
 * Stable Horde
 *
 * The API documentation for the Stable Horde
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StableHorde.Api.Client.OpenAPIDateConverter;

namespace StableHorde.Api.Model
{
    /// <summary>
    /// WorkerKudosDetails
    /// </summary>
    [DataContract(Name = "WorkerKudosDetails")]
    public partial class WorkerKudosDetails : IEquatable<WorkerKudosDetails>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkerKudosDetails" /> class.
        /// </summary>
        /// <param name="generated">How much Kudos this worker has received for generating images.</param>
        /// <param name="uptime">How much Kudos this worker has received for staying online longer.</param>
        public WorkerKudosDetails(decimal generated = default(decimal), int uptime = default(int))
        {
            this.Generated = generated;
            this.Uptime = uptime;
        }

        /// <summary>
        /// How much Kudos this worker has received for generating images
        /// </summary>
        /// <value>How much Kudos this worker has received for generating images</value>
        [DataMember(Name = "generated", EmitDefaultValue = false)]
        public decimal Generated { get; set; }

        /// <summary>
        /// How much Kudos this worker has received for staying online longer
        /// </summary>
        /// <value>How much Kudos this worker has received for staying online longer</value>
        [DataMember(Name = "uptime", EmitDefaultValue = false)]
        public int Uptime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkerKudosDetails {\n");
            sb.Append("  Generated: ").Append(Generated).Append("\n");
            sb.Append("  Uptime: ").Append(Uptime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WorkerKudosDetails);
        }

        /// <summary>
        /// Returns true if WorkerKudosDetails instances are equal
        /// </summary>
        /// <param name="input">Instance of WorkerKudosDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WorkerKudosDetails input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Generated == input.Generated ||
                    this.Generated.Equals(input.Generated)
                ) && 
                (
                    this.Uptime == input.Uptime ||
                    this.Uptime.Equals(input.Uptime)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Generated.GetHashCode();
                hashCode = (hashCode * 59) + this.Uptime.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
